### ISSUE TITLE
Any chance you could port this to Firefox and add https://bright.uvic.ca/?

### ISSUE THREAD

**Issue by lwunruh** [WesselvanDam/bs-extension#1]

**Comment by WesselvanDam** [comment]
Thanks for filing an issue! I thought that Firefox already allows users to open PDF's in a new tab by right-clicking on the file; is that correct? For that reason, I had not yet ported it to Firefox.

**Comment by WesselvanDam** [comment]
@lwunruh I have ported the extension to Firefox, it is available [here](https://addons.mozilla.org/en-GB/firefox/addon/brightspace-open-in-new-tab/). I have not tested it myself, as I don't have Firefox, but the required changes were minor so I expect it to work. Let me know otherwise :)
